[build]
  # Directory to deploy (current directory)
  publish = "."
  # No build command needed for static files
  command = ""

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Handle article pages with clean URLs
[[redirects]]
  from = "/news/:slug"
  to = "/news-article.html?slug=:slug"
  status = 200

# Handle direct access to HTML files without .html extension
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/news"
  to = "/news.html"
  status = 200

# Catch-all for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://kgdqqpskaetkrirrxugd.supabase.co; connect-src 'self' https://kgdqqpskaetkrirrxugd.supabase.co; frame-src 'self' https://*.supabase.co;"
    Access-Control-Allow-Origin = "*"
    
[dev]
  # Local development settings
  framework = "html"
  port = 3000
  targetPort = 3000
  publish = "."
  
[context.production]
  # Production-specific settings
  command = ""
  environment = { NODE_ENV = "production" }
